增加了指定文件/目录的编码/解码功能
lc6464/Base16384Coder-Console pull request #3
Opened 2023-08-29 11:46 UTC by execute233

使用了多一行的代码，实现了更多的功能。

2023-08-30 00:51 UTC, execute233 commented
？？？

2023-08-30 00:53 UTC, lc6464 commented
我 LC6464.Base16384 都还没发正式版，你这个急什么？

2023-08-30 00:53 UTC, execute233 commented
6

2023-08-30 00:54 UTC, lc6464 commented
你先帮我把 main 的剩下的 public 方法测了吧😑

2023-08-30 00:54 UTC, execute233 commented
你不是已经preview了吗？赶紧升级为release吧。

2023-08-30 00:55 UTC, lc6464 commented
测都没测完😑😑😑

2023-08-30 00:55 UTC, execute233 commented
除了有关Stream的方法都测过了。因为有关Stream的方法不知道是我的问题还是你的问题。

2023-08-30 01:00 UTC, lc6464 commented
文件开头有个 0xFE 0xFF，不参与解码的，你是不是没有去掉啊？

2023-08-30 01:20 UTC, execute233 commented
有没有种可能，你的DecodeFromFileToNewFile已经有了？

2023-09-10 07:01 UTC, execute233 commented
咋还不合并呢？

2023-09-13 15:26 UTC, lc6464 commented
类库 v2.0.0-RC.1 已发布。
记得测试，测试完成即可转正式版。
转完正式版即可审核此 PR.

2023-09-13 15:38 UTC, lc6464 commented
你也可以考虑在 Shared 最后加上 CopyToHGlobal 或者 CopyToNewHGlobal 之类的，不过我觉得没必要。

2023-09-14 04:22 UTC, lc6464 requested changes
其实我的建议是，
``` pwsh
Base16384.Net.exe <"e" | "d"> <source | "-"> <out | "-">
```
"-" 代表 Standard IO
source 若为文件，则直接处理，输出文件名为 out。
source 若为文件夹，则按我一开始的方案遍历并输出到文件夹 out。

2023-09-14 04:24 UTC, lc6464 commented
> 其实我的建议是，
> ``` pwsh
> Base16384.Net.exe <"e" | "d"> <source | "-"> <out | "-">
> ```
> "-" 代表 Standard IO
> source 若为文件，则直接处理，输出文件名为 out。
> source 若为文件夹，则按我一开始的方案遍历并输出到文件夹 out。

另外，如果 out 为 stdout，则不做任何 Console.WriteLine 自然语言提醒，出现什么问题直接 return (not 0)。

2023-09-28 23:57 UTC, execute233 commented
-_-

2023-09-29 01:27 UTC, lc6464 commented
你先看看能不能帮我把那个修了吧🤔

2023-09-29 03:00 UTC, execute233 commented
6

2023-09-29 04:03 UTC, execute233 commented
Standard IO？stdout？有关这些的不会写。-_-

2023-09-29 04:06 UTC, lc6464 commented
你先把那个 UTF8 的问题修了吧。

2023-09-29 05:53 UTC, execute233 commented
有没有种可能，我已经发PR了？

2023-09-30 02:33 UTC, execute233 commented
> 其实我的建议是，
> 
> ```powershell
> Base16384.Net.exe <"e" | "d"> <source | "-"> <out | "-">
> ```
> 
> "-" 代表 Standard IO source 若为文件，则直接处理，输出文件名为 out。 source 若为文件夹，则按我一开始的方案遍历并输出到文件夹 out。

输出文件打算都改名为 源文件+.En/Decode

2023-09-30 05:37 UTC, lc6464 commented
你都写了这么多了再加一个处理很难吗？😑

2023-10-04 04:44 UTC, execute233 commented
> 其实我的建议是，
> 
> ```powershell
> Base16384.Net.exe <"e" | "d"> <source | "-"> <out | "-">
> ```
> 
> "-" 代表 Standard IO source 若为文件，则直接处理，输出文件名为 out。 source 若为文件夹，则按我一开始的方案遍历并输出到文件夹 out。

输出文件名应该是原文件名+".out"吧？

2023-10-04 04:45 UTC, execute233 commented
我觉得应该往Console输出提示文件到哪里了,也可以提示是否成功。

2023-10-04 04:46 UTC, lc6464 commented
> 输出文件名应该是原文件名+".out"吧？

你是真没理解还是假没理解啊？
输出文件名由用户决定。

2023-10-04 04:50 UTC, lc6464 commented
> 我觉得应该往Console输出提示文件到哪里了,也可以提示是否成功。

如果不是 Std out 那就输出，如果是，那就不输出。

2023-10-04 04:50 UTC, execute233 commented
万一用户懒得写输出文件名呢？

2023-10-04 04:52 UTC, lc6464 commented
> 万一用户懒得写输出文件名呢？

在输入文件名的基础上添加 .encoded/.decoded

2023-10-04 04:59 UTC, execute233 commented
standard IO真不知道咋写 --_--

2023-10-04 05:02 UTC, execute233 commented
standard IO真不知道咋写 --_--

2023-10-04 05:03 UTC, lc6464 commented
OpenStandardIn

2023-10-04 05:03 UTC, execute233 commented
standard IO真不知道咋写 --_--

2023-10-19 00:03 UTC, lc6464 commented
Your ReadMe needs to be perfected.
And, some parts of code, such as file opening, may can be refined.

2023-10-19 00:05 UTC, lc6464 commented
I will fully review them when I come back to my dormitory.

2023-10-19 14:39 UTC, lc6464 requested changes
Because of the code of poor quality and the readme, it can not be merged.
But thank you for your PR.
If you still want to contribute this project, please optimize your code, thank you.

2023-10-22 05:08 UTC, closed without merging